---

- name: Deploy 'dropwizard-rest-stub'
  hosts: all
  vars:
    service_file: /etc/init.d/dropwizard
  tasks:

    - name: Create folders
      file:
        path: /var/dropwizard-rest-stub/
        state: directory
        force: true